// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByasJ195VDlce2neufNzYP0IGDSvV0PVA',
    appId: '1:901618325658:web:9505cd42ac6b5c4b0fa723',
    messagingSenderId: '901618325658',
    projectId: 'ilya-aygistov',
    authDomain: 'ilya-aygistov.firebaseapp.com',
    storageBucket: 'ilya-aygistov.appspot.com',
    measurementId: 'G-J1T4H7SPNE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3q8kSxwC0lXtlSkVhGLW2Rm4Tp7QCtGM',
    appId: '1:901618325658:android:5bdc656db4bb30ab0fa723',
    messagingSenderId: '901618325658',
    projectId: 'ilya-aygistov',
    storageBucket: 'ilya-aygistov.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcOmWQlEAEetUe_8ViwrR_uJx7-gRnsls',
    appId: '1:901618325658:ios:21653a5e5c69c35a0fa723',
    messagingSenderId: '901618325658',
    projectId: 'ilya-aygistov',
    storageBucket: 'ilya-aygistov.appspot.com',
    iosBundleId: 'com.example.flutterElijah',
  );
}